version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8060:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
    depends_on:
      - api
      - minio
  api:
    image: cocopam/ureka-server:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=mybucket
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8001
    depends_on:
      - postgres
      - minio
      - chroma
    networks:
      - internal

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - internal


  chroma:
    image: chromadb/chroma:1.0.5
    environment:
      - CHROMA_DB_DIR=/data
    volumes:
      - chroma_data:/data
    restart: unless-stopped
    networks:
      - internal


volumes:
  postgres_data:
  minio_data:
  chroma_data:

networks:
  internal: