name: Run Build and Test

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache uv virtual environment
        uses: actions/cache@v3
        with:
          path: .uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Create junit directory
        run: mkdir -p junit

      - name: Run tests
        run: |
          uv run pytest \
            --doctest-modules \
            --continue-on-collection-errors \
            --junitxml=junit/test-results-${{ matrix.python-version }}.xml || true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: junit/test-results-*.xml
