name: Run Build and Test

permissions:
  contents: read

on:
  push:
    branches:
      - main # 혹은 'master', 또는 테스트하고 싶은 브랜치 이름
  pull_request:

jobs:
  build:
    env:
      IMAGE_NAME: ureka-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          context: .
          cache-from: type=registry,ref=${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          annotations: ${{ steps.meta.outputs.annotations }}

  test:
    env:
      IMAGE_NAME: ureka-server
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        run: |
          docker run --rm --name test-container -v ./junit:/app/junit/ ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} uv run pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml || true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: junit/test-results-*.xml
