name: Run Python Tests

on:
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_run:
    workflows:
      - Build Docker Image
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ureka-server
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/ureka-server.tar
          docker image ls -a

      - name: Run tests
        run: |
          docker run --name test-container ureka-server uv run pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
          docker cp test-container:~/junit/test-results-${{ matrix.python-version }}.xml junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
